import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Mathly — Terms of Use | BalkanBit",
  description:
    "Terms of use for the Mathly mobile application, including subscription and auto-renewal terms.",
};

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold text-white mb-4">{title}</h2>
      <div className="space-y-4 text-[15px] leading-relaxed text-[#8ca0c8]">
        {children}
      </div>
    </section>
  );
}

export default function MathlyTerms() {
  return (
    <main className="min-h-screen">
      <header className="border-b border-white/[0.07]">
        <div className="max-w-3xl mx-auto px-6 py-6 flex items-center justify-between">
          <Link href="/" className="font-mono text-lg font-bold">
            <span className="text-[#4f8fff]">Balkan</span>Bit
          </Link>
          <span className="text-xs font-mono text-[#4f8fff] tracking-widest uppercase">
            Legal
          </span>
        </div>
      </header>

      <article className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-xs font-mono text-[#4f8fff] tracking-widest uppercase mb-4">
          Mathly
        </p>
        <h1 className="text-3xl md:text-4xl font-bold text-white mb-3">
          Terms of Use
        </h1>
        <p className="text-sm text-[#8ca0c8] mb-12">
          Effective date: August 15, 2026 · Applies to the Mathly mobile
          application for iOS and Android
        </p>

        <Section title="1. Agreement">
          <p>
            These Terms of Use are an agreement between you and
            &ldquo;Pazaruvai Umno&rdquo; EOOD, UIC 206373314, Sofia, Bulgaria
            (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By using the Mathly
            application (&ldquo;the App&rdquo;) you accept these terms. On iOS,
            Apple&rsquo;s standard Licensed Application End User License
            Agreement also applies to the extent it is not in conflict with
            these terms.
          </p>
        </Section>

        <Section title="2. The service">
          <p>
            The App reads math and science problems from a photo or typed input
            and returns worked, step-by-step solutions, graphs, and follow-up
            explanations. Solutions are generated by an AI model. While we check
            each answer before showing it, AI systems can still make mistakes:
            solutions are a study aid, not a guarantee of correctness, and are
            not a substitute for your own work, your teacher, or professional
            advice.
          </p>
          <p>
            You are responsible for how you use the App&rsquo;s output. Using it
            in a way that breaks your school&rsquo;s or institution&rsquo;s
            rules on academic honesty is your responsibility, not ours.
          </p>
          <p>
            You may only submit content you have the right to submit, and you
            should not photograph documents containing personal information
            about other people.
          </p>
        </Section>

        <Section title="3. Subscriptions">
          <p>
            Unlimited solving and the other premium features require the{" "}
            <strong className="text-white">Mathly Pro</strong> auto-renewing
            subscription, purchased through the Apple App Store or Google Play:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong className="text-white">Yearly — $39.99 per year</strong>,
              offered with a 3-day free trial for new subscribers. If you do not
              cancel before the trial ends, the subscription begins and the
              yearly price is charged.
            </li>
            <li>
              <strong className="text-white">Weekly — $6.99 per week.</strong>
            </li>
            <li>
              Prices are in US dollars and may vary by territory; the exact
              price for your region is shown on the purchase screen before you
              confirm.
            </li>
            <li>
              Payment is charged to your App Store or Google Play account at
              confirmation of purchase.
            </li>
            <li>
              The subscription renews automatically for the same period unless
              cancelled at least 24 hours before the end of the current period.
              Your account is charged for renewal within 24 hours prior to the
              end of the current period.
            </li>
            <li>
              You can manage or cancel your subscription anytime in your App
              Store or Google Play account settings. Any unused portion of a
              free trial is forfeited when you purchase a subscription.
            </li>
            <li>
              Refunds are handled by Apple or Google under their respective
              store policies.
            </li>
          </ul>
        </Section>

        <Section title="4. Acceptable use">
          <p>
            You may not reverse engineer the App, resell or redistribute its
            output as your own service, submit content you have no right to
            submit, or attempt to circumvent usage limits or subscription
            entitlements.
          </p>
        </Section>

        <Section title="5. Privacy">
          <p>
            How we handle your problem photos and other data is described in the{" "}
            <Link
              href="/mathly/privacy-policy"
              className="text-[#4f8fff] hover:underline"
            >
              Privacy Policy
            </Link>
            , which forms part of these terms.
          </p>
        </Section>

        <Section title="6. Liability">
          <p>
            The App is provided &ldquo;as is&rdquo;. To the maximum extent
            permitted by law, we are not liable for indirect or consequential
            damages arising from your use of the App, including any consequence
            of relying on a solution it produced. Nothing in these terms limits
            rights you have as a consumer under Bulgarian or EU law.
          </p>
        </Section>

        <Section title="7. Changes and contact">
          <p>
            We may update these terms; material changes will be announced in the
            App. Continued use after changes take effect constitutes acceptance.
            Contact:{" "}
            <a
              href="mailto:manol@balkanbit.app"
              className="text-[#4f8fff] hover:underline"
            >
              manol@balkanbit.app
            </a>
            . These terms are governed by the law of the Republic of Bulgaria.
          </p>
        </Section>

        <footer className="pt-8 border-t border-white/[0.07] text-sm text-[#8ca0c8]">
          <p>
            &ldquo;Pazaruvai Umno&rdquo; EOOD · UIC 206373314 · Sofia,
            Bulgaria ·{" "}
            <Link
              href="/mathly/privacy-policy"
              className="text-[#4f8fff] hover:underline"
            >
              Privacy Policy
            </Link>{" "}
            ·{" "}
            <Link
              href="/mathly/support"
              className="text-[#4f8fff] hover:underline"
            >
              Support
            </Link>
          </p>
        </footer>
      </article>
    </main>
  );
}
